name: deadspace-web

services:
  postgres:
    image: postgres
    restart: always
    environment:
      # - POSTGRES_DB_FILE=/run/secrets/POSTGRES_DB
      # - POSTGRES_USER_FILE=/run/secrets/POSTGRES_USER
      # - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    # secrets:
    #   - POSTGRES_DB
    #   - POSTGRES_USER
    #   - POSTGRES_PASSWORD

  web:
    image: deadspace-web-ui
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - NEXT_PUBLIC_UPLOADTHING_APP_ID
        - UPLOADTHING_SECRET
        - DB_URL
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    ports:
      - "3000:3000"
    secrets:
      - NEXT_PUBLIC_UPLOADTHING_APP_ID
      - NEXT_PUBLIC_BASE_URL
      - UPLOADTHING_SECRET
      - DB_URL
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - GOOGLE_AUTH_CLIENT_ID
      - GOOGLE_AUTH_CLIENT_SECRET

volumes:
  pg_data:

secrets:
  NEXT_PUBLIC_UPLOADTHING_APP_ID:
    file: ./secrets/NEXT_PUBLIC_UPLOADTHING_APP_ID
  UPLOADTHING_SECRET:
    file: ./secrets/UPLOADTHING_SECRET
  DB_URL:
    file: ./secrets/DB_URL
  POSTGRES_DB:
    file: ./secrets/POSTGRES_DB
  POSTGRES_USER:
    file: ./secrets/POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD
  GOOGLE_AUTH_CLIENT_ID:
    file: ./secrets/GOOGLE_AUTH_CLIENT_ID
  GOOGLE_AUTH_CLIENT_SECRET:
    file: ./secrets/GOOGLE_AUTH_CLIENT_SECRET
  NEXT_PUBLIC_BASE_URL:
    file: ./secrets/NEXT_PUBLIC_BASE_URL

networks:
  default:
    name: deadspace-network
