name: deadspace-web
services:
    postgres:
      image: postgres
      restart: always
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      healthcheck:
        test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
        interval: 10s
        timeout: 5s
        retries: 5
      ports:
        - 5432:5432
      volumes:
        - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

