
name: deadspace-web
services:
  web:
    image: "ghcr.io/listlessbird/deadspace-web:latest"
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    secrets:
      - NEXT_PUBLIC_UPLOADTHING_APP_ID
      - NEXT_PUBLIC_BASE_URL
      - UPLOADTHING_SECRET
      - DB_URL
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - GOOGLE_AUTH_CLIENT_ID
      - GOOGLE_AUTH_CLIENT_SECRET

secrets:
  NEXT_PUBLIC_UPLOADTHING_APP_ID:
    file: ./secrets/NEXT_PUBLIC_UPLOADTHING_APP_ID
  UPLOADTHING_SECRET:
    file: ./secrets/UPLOADTHING_SECRET
  DB_URL:
    file: ./secrets/DB_URL
  POSTGRES_DB:
    file: ./secrets/POSTGRES_DB
  POSTGRES_USER:
    file: ./secrets/POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD
  GOOGLE_AUTH_CLIENT_ID:
    file: ./secrets/GOOGLE_AUTH_CLIENT_ID
  GOOGLE_AUTH_CLIENT_SECRET:
    file: ./secrets/GOOGLE_AUTH_CLIENT_SECRET
  NEXT_PUBLIC_BASE_URL:
    file: ./secrets/NEXT_PUBLIC_BASE_URL

networks:
  default:
    name: deadspace-network

